//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ApplicationCore.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ApplicationCore.Resource.ViResource", typeof(ViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thất bại..
        /// </summary>
        public static string AddFail {
            get {
                return ResourceManager.GetString("AddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thành công..
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản ngân hàng.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh ngân hàng.
        /// </summary>
        public static string BankBranchName {
            get {
                return ResourceManager.GetString("BankBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thất bại..
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường &apos;{0}&apos; bị trùng ( {1} - {2} )..
        /// </summary>
        public static string DuplicateFieldDev {
            get {
                return ResourceManager.GetString("DuplicateFieldDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin &apos;{0}&apos; bị trùng vui lòng nhập lại..
        /// </summary>
        public static string DuplicateFieldUsr {
            get {
                return ResourceManager.GetString("DuplicateFieldUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh nhân viên.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string EmployeePosition {
            get {
                return ResourceManager.GetString("EmployeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string GenderName {
            get {
                return ResourceManager.GetString("GenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND/ Căn cước công dân..
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp CMND/ Căn cước công dân..
        /// </summary>
        public static string IdentityPlace {
            get {
                return ResourceManager.GetString("IdentityPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường &apos;{0}&apos; nhập sai ( {1} - {2} )..
        /// </summary>
        public static string InvalidFieldDev {
            get {
                return ResourceManager.GetString("InvalidFieldDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin &apos;{0}&apos; bị nhập sai vui lòng nhập lại..
        /// </summary>
        public static string InvalidFieldUsr {
            get {
                return ResourceManager.GetString("InvalidFieldUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường &apos;{0}&apos; không đúng định dạng ( {1} - {2} )..
        /// </summary>
        public static string InvalidFormatDev {
            get {
                return ResourceManager.GetString("InvalidFormatDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không đúng định dạng vui lòng nhập lại..
        /// </summary>
        public static string InvalidFormatUsr {
            get {
                return ResourceManager.GetString("InvalidFormatUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài trường &apos;{0}&apos;(&apos;{1}&apos; - độ dài: {2}) vượt quá độ dài cho phép({3})..
        /// </summary>
        public static string InvalidLengthDev {
            get {
                return ResourceManager.GetString("InvalidLengthDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài của &apos;{0}&apos; vượt quá cho phép vui lòng nhập lại..
        /// </summary>
        public static string InvalidLengthUsr {
            get {
                return ResourceManager.GetString("InvalidLengthUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Tháng.
        /// </summary>
        public static string MonthYear {
            get {
                return ResourceManager.GetString("MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường &apos;{0}&apos; không được để trống..
        /// </summary>
        public static string NonEmptyFieldDev {
            get {
                return ResourceManager.GetString("NonEmptyFieldDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin &apos;{0}&apos; không được để trống vui lòng nhập lại..
        /// </summary>
        public static string NonEmptyFieldUsr {
            get {
                return ResourceManager.GetString("NonEmptyFieldUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; {0}&apos; không tồn tại ( {1} - {2} )..
        /// </summary>
        public static string NonExistIdDev {
            get {
                return ResourceManager.GetString("NonExistIdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &apos;{0}&apos; không tồn tại vui lòng nhập lại..
        /// </summary>
        public static string NonExistIdUsr {
            get {
                return ResourceManager.GetString("NonExistIdUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang.
        /// </summary>
        public static string PageIndex {
            get {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước trang.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di dộng..
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu {0} phải lớn hơn 0 ( {1} - {2})..
        /// </summary>
        public static string PositiveValueDev {
            get {
                return ResourceManager.GetString("PositiveValueDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị của {0} phải lớn hơn 0..
        /// </summary>
        public static string PositiveValueUsr {
            get {
                return ResourceManager.GetString("PositiveValueUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống..
        /// </summary>
        public static string SystemErrorDev {
            get {
                return ResourceManager.GetString("SystemErrorDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi hệ thống xảy ra vui lòng liên hệ MISA..
        /// </summary>
        public static string SystemErrorUsr {
            get {
                return ResourceManager.GetString("SystemErrorUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định..
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thất bại..
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
